services:
  postgres: 
    image: postgres:17.4-alpine3.21                                             #Escolhendo a imagem para usar o Postgres
    container_name: postgres_db                                                 #Nome do Container
    env_file:                                                                   #Passando um arquivo que diz quais as variáveis de ambiente
      - .env
    environment:                                                                #Setando algumas variáveis de ambiente para o Postgres
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER                                         
      POSTGRES_DB: $DB_NAME
    volumes:                                                                    #Passando um volume para o container (do local para o container)
      - ./init-db:/docker-entrypoint-initdb.d                                   #Banco inicial do Postgres (está sendo passado um script)
    networks:                                                                   #Setando uma Network para a comunicação dos containers
      network_default:
    healthcheck:                                                                #Healthycheck que me diz se o container está funcional
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always                                                             #Caso não consiga subir, restartar sempre

#---------------------------------------------------------------     
#---------------------------------------------------------------  
  app-python:                                                                   
    container_name: app_python                                                  #Definindo o nome do Container
    build: .                                                                    #Dizendo que a construção dele é baseada em um Dockerfile local
    ports:                                                                      #Passando a porta 5000 do container para a local na porta 8080
      - "8080:5000"
    env_file:                                                                   #Passando um arquivo de variáveis de ambiente
      - .env
    depends_on:                                                                 #Sobe o container apenas se o container do Postgres estiver healthy
      postgres:
        condition: service_healthy                                              
    networks:                                                                   #Passando a Network
      - network_default
    restart: unless-stopped                                                     
#--------------------------------------------------------------- 
#--------------------------------------------------------------- 
networks:                                                                       #Setando a network default
  network_default: